### ISSUE TITLE
search_vec is missing topk param 

### ISSUE THREAD

**Issue by alielabridi** [LSIR/DIS2019#2]
https://github.com/LSIR/DIS2019/blob/master/Exercises/notebooks/01.Vector_Space_Retrieval/Vector_Space_Retrieval.ipynb

Exercise 2.2: Compute the MAP score : search_vec is missing topk param

and   gt = search_vec_sklearn(**queries[0]**, features) should be changed

**Comment by chithangduong** [comment]
Thanks @alielabridi. I have fixed both of them.
